# GitHub Sponsors configuration for LionAGI QE Fleet
# Support the development of AI-powered quality engineering tools

# Custom sponsorship links
custom:
  - "https://github.com/proffesor-for-testing/lionagi-qe-fleet/blob/main/SPONSORS.md"
